# Generated by Django 3.1.4 on 2020-12-14 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20201213_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='place',
            name='maps_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_id',
            field=models.TextField(),
        ),
    ]
